"""Versioned, deterministic Phase G configuration."""

from __future__ import annotations

from datetime import time

DECISION_MEMORY_VERSION = "decision-memory-v1"
OUTCOME_VERSION = "decision-outcome-v1"
RETRIEVAL_VERSION = "memory-retrieval-v1"
DAILY_REVIEW_VERSION = "daily-review-v1"

OUTCOME_HORIZONS = (1, 5, 10, 20, 60, 120)
DECISION_EXECUTION_WINDOW_TRADING_DAYS = 2
EXECUTION_FULL_RATIO_MIN = 0.80
RETRIEVAL_MIN_COVERAGE = 0.60
RETRIEVAL_DEFAULT_LIMIT = 5
RETRIEVAL_MAX_LIMIT = 10
RETRIEVAL_LOOKBACK_DAYS = 365 * 3
RETRIEVAL_PREFILTER_LIMIT = 1000
MINIMUM_STATS_SAMPLE = 10
CHINA_SESSION_CLOSE = time(15, 0)

ALIGNMENTS = frozenset({
    "FOLLOWED",
    "PARTIAL",
    "IGNORED",
    "OPPOSITE",
    "UNRESOLVED",
    "NOT_APPLICABLE",
})

OUTCOME_STATUSES = frozenset({
    "PENDING",
    "VALID",
    "DEGRADED",
    "NOT_APPLICABLE",
    "WAITING_DATA",
    "BLOCKED",
    "UNAVAILABLE",
})

__all__ = [
    "ALIGNMENTS",
    "CHINA_SESSION_CLOSE",
    "DAILY_REVIEW_VERSION",
    "DECISION_EXECUTION_WINDOW_TRADING_DAYS",
    "DECISION_MEMORY_VERSION",
    "EXECUTION_FULL_RATIO_MIN",
    "MINIMUM_STATS_SAMPLE",
    "OUTCOME_HORIZONS",
    "OUTCOME_STATUSES",
    "OUTCOME_VERSION",
    "RETRIEVAL_DEFAULT_LIMIT",
    "RETRIEVAL_LOOKBACK_DAYS",
    "RETRIEVAL_MAX_LIMIT",
    "RETRIEVAL_MIN_COVERAGE",
    "RETRIEVAL_PREFILTER_LIMIT",
    "RETRIEVAL_VERSION",
]
